import { Task, Project, UserProfile } from './supabase';

export const demoUsers: UserProfile[] = [
  { id: '1', email: 'rahul@example.com', name: 'Rahul Sharma', role: 'Admin', created_at: new Date().toISOString() },
  { id: '2', email: 'priya@example.com', name: 'Priya Patel', role: 'Member', created_at: new Date().toISOString() },
  { id: '3', email: 'amit@example.com', name: 'Amit Singh', role: 'Member', created_at: new Date().toISOString() },
  { id: '4', email: 'neha@example.com', name: 'Neha Gupta', role: 'Member', created_at: new Date().toISOString() },
];

export const demoProjects: (Project & { admin: { name: string } })[] = [
  { id: 'p1', name: 'E-commerce Redesign', description: 'Overhaul the main shopping experience for Q3.', admin_id: '1', created_at: new Date(Date.now() - 1000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p2', name: 'Mobile App Launch', description: 'v1.0 release for iOS and Android platforms.', admin_id: '1', created_at: new Date(Date.now() - 2000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p3', name: 'Marketing Campaign', description: 'Summer promotional materials and ad creatives.', admin_id: '1', created_at: new Date(Date.now() - 3000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p4', name: 'Security Audit', description: 'Annual penetration testing and compliance checks.', admin_id: '1', created_at: new Date(Date.now() - 4000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p5', name: 'Customer Portal', description: 'Self-service dashboard for enterprise clients.', admin_id: '1', created_at: new Date(Date.now() - 5000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p6', name: 'Analytics Dashboard', description: 'Internal BI tools and data visualization.', admin_id: '1', created_at: new Date(Date.now() - 6000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p7', name: 'HR Onboarding System', description: 'Automated employee enrollment flow.', admin_id: '1', created_at: new Date(Date.now() - 7000000000).toISOString(), admin: { name: 'Rahul Sharma' } },
  { id: 'p8', name: 'Cloud Migration', description: 'Moving legacy services to AWS.', admin_id: '1', created_at: new Date(Date.now() - 8000000000).toISOString(), admin: { name: 'Rahul Sharma' } }
];

export const demoTasks: (Task & { project: { name: string }, assignee: { name: string, id: string } | null })[] = [
  { id: 't1', title: 'Design System Update', description: 'Update color palette and typography.', project_id: 'p1', assigned_to: '2', status: 'Done', deadline: new Date(Date.now() - 86400000).toISOString(), created_at: new Date(Date.now() - 1000000000).toISOString(), project: { name: 'E-commerce Redesign' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't2', title: 'API Integration', description: 'Connect frontend to payment gateway.', project_id: 'p1', assigned_to: '3', status: 'In Progress', deadline: new Date(Date.now() + 86400000).toISOString(), created_at: new Date(Date.now() - 500000000).toISOString(), project: { name: 'E-commerce Redesign' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't3', title: 'App Store Submission', description: 'Prepare screenshots and metadata.', project_id: 'p2', assigned_to: '4', status: 'To Do', deadline: new Date(Date.now() + 172800000).toISOString(), created_at: new Date(Date.now() - 200000000).toISOString(), project: { name: 'Mobile App Launch' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't4', title: 'Social Media Assets', description: 'Create banners for LinkedIn and Twitter.', project_id: 'p3', assigned_to: '2', status: 'Done', deadline: new Date(Date.now() - 86400000 * 2).toISOString(), created_at: new Date(Date.now() - 900000000).toISOString(), project: { name: 'Marketing Campaign' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't5', title: 'Database Optimization', description: 'Add indexes to user tables.', project_id: 'p4', assigned_to: '3', status: 'In Progress', deadline: new Date(Date.now() + 86400000 * 3).toISOString(), created_at: new Date(Date.now() - 400000000).toISOString(), project: { name: 'Security Audit' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't6', title: 'Login UI', description: 'Implement SSO buttons.', project_id: 'p5', assigned_to: '4', status: 'Done', deadline: new Date(Date.now() - 86400000 * 5).toISOString(), created_at: new Date(Date.now() - 600000000).toISOString(), project: { name: 'Customer Portal' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't7', title: 'Weekly Report Generation', description: 'Automate PDF creation.', project_id: 'p6', assigned_to: '2', status: 'To Do', deadline: new Date(Date.now() - 86400000).toISOString(), created_at: new Date(Date.now() - 300000000).toISOString(), project: { name: 'Analytics Dashboard' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't8', title: 'Welcome Email Template', description: 'Draft text for new hires.', project_id: 'p7', assigned_to: '3', status: 'In Progress', deadline: new Date(Date.now() + 86400000 * 4).toISOString(), created_at: new Date(Date.now() - 250000000).toISOString(), project: { name: 'HR Onboarding System' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't9', title: 'S3 Bucket Configuration', description: 'Set up cross-region replication.', project_id: 'p8', assigned_to: '4', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 7).toISOString(), created_at: new Date(Date.now() - 150000000).toISOString(), project: { name: 'Cloud Migration' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't10', title: 'User Onboarding Flow', description: 'Design screens for first-time users.', project_id: 'p2', assigned_to: '2', status: 'Done', deadline: new Date(Date.now() - 86400000 * 3).toISOString(), created_at: new Date(Date.now() - 1100000000).toISOString(), project: { name: 'Mobile App Launch' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't11', title: 'Cart Checkout Bug', description: 'Fix rounding error in total calculation.', project_id: 'p1', assigned_to: '3', status: 'In Progress', deadline: new Date(Date.now() + 43200000).toISOString(), created_at: new Date(Date.now() - 80000000).toISOString(), project: { name: 'E-commerce Redesign' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't12', title: 'Push Notification Setup', description: 'Integrate Firebase Cloud Messaging.', project_id: 'p2', assigned_to: '4', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 2).toISOString(), created_at: new Date(Date.now() - 100000000).toISOString(), project: { name: 'Mobile App Launch' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't13', title: 'Email Newsletter', description: 'Draft Q3 updates for subscribers.', project_id: 'p3', assigned_to: '2', status: 'Done', deadline: new Date(Date.now() - 86400000 * 10).toISOString(), created_at: new Date(Date.now() - 1200000000).toISOString(), project: { name: 'Marketing Campaign' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't14', title: 'Vulnerability Scan', description: 'Run Nessus on production servers.', project_id: 'p4', assigned_to: '3', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 5).toISOString(), created_at: new Date(Date.now() - 200000000).toISOString(), project: { name: 'Security Audit' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't15', title: 'Client Feedback Form', description: 'Create survey for portal users.', project_id: 'p5', assigned_to: '4', status: 'Done', deadline: new Date(Date.now() - 86400000 * 8).toISOString(), created_at: new Date(Date.now() - 1500000000).toISOString(), project: { name: 'Customer Portal' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't16', title: 'Data Pipeline Fix', description: 'Resolve ETL job failures.', project_id: 'p6', assigned_to: '2', status: 'In Progress', deadline: new Date(Date.now() + 86400000).toISOString(), created_at: new Date(Date.now() - 350000000).toISOString(), project: { name: 'Analytics Dashboard' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't17', title: 'Offer Letter Template', description: 'Update legal jargon in PDFs.', project_id: 'p7', assigned_to: '3', status: 'Done', deadline: new Date(Date.now() - 86400000 * 4).toISOString(), created_at: new Date(Date.now() - 800000000).toISOString(), project: { name: 'HR Onboarding System' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't18', title: 'IAM Roles Review', description: 'Audit AWS permissions.', project_id: 'p8', assigned_to: '4', status: 'In Progress', deadline: new Date(Date.now() + 86400000 * 3).toISOString(), created_at: new Date(Date.now() - 450000000).toISOString(), project: { name: 'Cloud Migration' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't19', title: 'Product Page SEO', description: 'Optimize meta tags and headers.', project_id: 'p1', assigned_to: '2', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 6).toISOString(), created_at: new Date(Date.now() - 50000000).toISOString(), project: { name: 'E-commerce Redesign' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't20', title: 'Offline Mode Testing', description: 'Verify app behavior without internet.', project_id: 'p2', assigned_to: '3', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 4).toISOString(), created_at: new Date(Date.now() - 120000000).toISOString(), project: { name: 'Mobile App Launch' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't21', title: 'Press Release Draft', description: 'Write announcement for new feature.', project_id: 'p3', assigned_to: '4', status: 'Done', deadline: new Date(Date.now() - 86400000 * 12).toISOString(), created_at: new Date(Date.now() - 1800000000).toISOString(), project: { name: 'Marketing Campaign' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't22', title: 'Penetration Testing', description: 'Hire external firm for black-box testing.', project_id: 'p4', assigned_to: '2', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 14).toISOString(), created_at: new Date(Date.now() - 10000000).toISOString(), project: { name: 'Security Audit' }, assignee: { name: 'Priya Patel', id: '2' } },
  { id: 't23', title: 'Billing Integration', description: 'Connect Stripe for invoice payments.', project_id: 'p5', assigned_to: '3', status: 'In Progress', deadline: new Date(Date.now() + 86400000 * 8).toISOString(), created_at: new Date(Date.now() - 600000000).toISOString(), project: { name: 'Customer Portal' }, assignee: { name: 'Amit Singh', id: '3' } },
  { id: 't24', title: 'BI Tool Training', description: 'Host session for marketing team.', project_id: 'p6', assigned_to: '4', status: 'Done', deadline: new Date(Date.now() - 86400000 * 15).toISOString(), created_at: new Date(Date.now() - 2000000000).toISOString(), project: { name: 'Analytics Dashboard' }, assignee: { name: 'Neha Gupta', id: '4' } },
  { id: 't25', title: 'Background Check API', description: 'Integrate Checkr for new employees.', project_id: 'p7', assigned_to: '2', status: 'To Do', deadline: new Date(Date.now() + 86400000 * 10).toISOString(), created_at: new Date(Date.now() - 80000000).toISOString(), project: { name: 'HR Onboarding System' }, assignee: { name: 'Priya Patel', id: '2' } },
];

export const demoActivity = [
  { id: 'a1', text: "Rahul completed task 'Login UI'", time: new Date(Date.now() - 3600000).toISOString(), user: 'Rahul' },
  { id: 'a2', text: "Priya created project 'E-commerce App'", time: new Date(Date.now() - 7200000).toISOString(), user: 'Priya' },
  { id: 'a3', text: "Amit commented on 'API Integration'", time: new Date(Date.now() - 18000000).toISOString(), user: 'Amit' },
  { id: 'a4', text: "Neha moved 'App Store Submission' to In Progress", time: new Date(Date.now() - 86400000).toISOString(), user: 'Neha' },
  { id: 'a5', text: "Rahul uploaded 'Q3 Design Assets'", time: new Date(Date.now() - 172800000).toISOString(), user: 'Rahul' },
];
